### ISSUE TITLE
show reviews

### ISSUE THREAD

**Issue by drma-tech** [drma-tech/SD#3]
show reviews, not only trailers and news

**Comment by drma-dev** [comment]
https://rapidapi.com/Prastiwar/api/metacriticapi/

**Comment by drma-dev** [comment]
https://rapidapi.com/apidojo/api/imdb8

free - 500 per month

**Comment by drma-dev** [comment]
https://www.metacritic.com/movie/puss-in-boots-the-last-wish/critic-reviews?sort-by=date
